# application.yml
# Server settings (ServerProperties)
server:
  port: 9099
  address: 127.0.0.1
  sessionTimeout: 30
  #contextPath: /springboot

# Tomcat specifics
tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

# logback
logging:
    config: classpath:logback-boot.xml

log:
    level:
        project: INFO
        program: INFO
    filePath: logs/app.log
    fileMaxSize: 50M
    moduleName: springboot
    package: cn.ifengkou.springboot
